// Map of Storyblok components to Astro components.
// This file is auto-updated by the 'storyblok:create-block' script.
// Please keep exports alphabetical.

export const storyblokComponents = {
  agenda_events_section: 'components/storyblok/AgendaEventsSection',
  agenda_page: 'components/storyblok/AgendaPage',
  biography_hero_section: 'components/storyblok/BiographyHeroSection',
  biography_page: 'components/storyblok/BiographyPage',
  career_highlight_item: 'components/storyblok/CareerHighlightItem',
  career_highlights_section: 'components/storyblok/CareerHighlightsSection',
  contact_info: 'components/storyblok/ContactInfo',
  cta_section: 'components/storyblok/CtaSection',
  editorial_image_section: 'components/storyblok/EditorialImageSection',
  editorial_text_section: 'components/storyblok/EditorialTextSection',
  event_card: 'components/storyblok/EventCard',
  event_highlight_item: 'components/storyblok/EventHighlightItem',
  events_grid: 'components/storyblok/EventsGrid',
  featured_works_section: 'components/storyblok/FeaturedWorksSection',
  footer_config: 'components/storyblok/FooterConfig',
  global_config: 'components/storyblok/GlobalConfig',
  header_config: 'components/storyblok/HeaderConfig',
  hero_section: 'components/storyblok/HeroSection',
  home_hero_section: 'components/storyblok/HomeHeroSection',
  home_page: 'components/storyblok/HomePage',
  image_text_section: 'components/storyblok/ImageTextSection',
  legal_links: 'components/storyblok/LegalLinks',
  media_gallery: 'components/storyblok/MediaGallery',
  navigation_item: 'components/storyblok/NavigationItem',
  navigation_menu: 'components/storyblok/NavigationMenu',
  page: 'components/storyblok/Page',
  press_quote: 'components/storyblok/PressQuote',
  seo: 'components/storyblok/Seo',
  site_identity: 'components/storyblok/SiteIdentity',
  social_profile_link: 'components/storyblok/SocialProfileLink',
  social_profiles: 'components/storyblok/SocialProfiles',
  text_section: 'components/storyblok/TextSection',
  upcoming_highlights_section: 'components/storyblok/UpcomingHighlightsSection',
  video_embed: 'components/storyblok/VideoEmbed',
  work_catalog_item: 'components/storyblok/WorkCatalogItem',
  work_highlight_card: 'components/storyblok/WorkHighlightCard',
  works_catalog_group: 'components/storyblok/WorksCatalogGroup',
  works_catalog_page: 'components/storyblok/WorksCatalogPage',
};
